CREATE TABLE code (
  code_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  task_id INT NULL,
  code LONGTEXT NULL,
  created_date TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  modified_date TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (task_id) REFERENCES task(task_id)
);